apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: proxus-server
  name: proxus-server
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: proxus-server
