apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: timescaledb
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: timescaledb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/chart-proxus: "true"
        io.kompose.service: timescaledb
    spec:
      containers:
        - args:
            - postgres
            - -c
            - shared_preload_libraries=timescaledb
            - -p
            - "5442"
          env:
            - name: POSTGRES_DB
              value: proxus
            - name: POSTGRES_PASSWORD
              value: proxus
            - name: POSTGRES_USER
              value: proxus
          image: timescale/timescaledb-ha:pg16
          name: timescaledb
          ports:
            - containerPort: 5442
              hostPort: 5442
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /home/postgres/pgdata/data
              name: proxus-db-volume
      restartPolicy: Always
      volumes:
        - name: proxus-db-volume
          persistentVolumeClaim:
            claimName: proxus-db-volume
