apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: timescaledb
  name: timescaledb
spec:
  type: LoadBalancer
  ports:
    - name: "5442"
      port: 5442
      targetPort: 5442
  selector:
    io.kompose.service: timescaledb
